//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.Web.UnitTest.WebWCF_test {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebWCF_test.IWebWCF")]
    public interface IWebWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebWCF/DoWork", ReplyAction="http://tempuri.org/IWebWCF/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebWCF/DoWork", ReplyAction="http://tempuri.org/IWebWCF/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebWCF/Minus", ReplyAction="http://tempuri.org/IWebWCF/MinusResponse")]
        int Minus(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebWCF/Minus", ReplyAction="http://tempuri.org/IWebWCF/MinusResponse")]
        System.Threading.Tasks.Task<int> MinusAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebWCFChannel : SOA.Web.UnitTest.WebWCF_test.IWebWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebWCFClient : System.ServiceModel.ClientBase<SOA.Web.UnitTest.WebWCF_test.IWebWCF>, SOA.Web.UnitTest.WebWCF_test.IWebWCF {
        
        public WebWCFClient() {
        }
        
        public WebWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int Minus(int x, int y) {
            return base.Channel.Minus(x, y);
        }
        
        public System.Threading.Tasks.Task<int> MinusAsync(int x, int y) {
            return base.Channel.MinusAsync(x, y);
        }
    }
}
