//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.Web.UnitTest.WebServiceTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceTest.MyWebServiceSoap")]
    public interface MyWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: 消息 MinusRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Minus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA.Web.UnitTest.WebServiceTest.MinusResponse Minus(SOA.Web.UnitTest.WebServiceTest.MinusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Minus", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA.Web.UnitTest.WebServiceTest.MinusResponse> MinusAsync(SOA.Web.UnitTest.WebServiceTest.MinusRequest request);
        
        // CODEGEN: 消息 UserListRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA.Web.UnitTest.WebServiceTest.UserListResponse UserList(SOA.Web.UnitTest.WebServiceTest.UserListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserList", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA.Web.UnitTest.WebServiceTest.UserListResponse> UserListAsync(SOA.Web.UnitTest.WebServiceTest.UserListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int ageField;
        
        private int sexField;
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("Age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Minus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MinusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SOA.Web.UnitTest.WebServiceTest.CustomSoapHeader CustomSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int iValueOne;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int iValueTwo;
        
        public MinusRequest() {
        }
        
        public MinusRequest(SOA.Web.UnitTest.WebServiceTest.CustomSoapHeader CustomSoapHeader, int iValueOne, int iValueTwo) {
            this.CustomSoapHeader = CustomSoapHeader;
            this.iValueOne = iValueOne;
            this.iValueTwo = iValueTwo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MinusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MinusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int MinusResult;
        
        public MinusResponse() {
        }
        
        public MinusResponse(int MinusResult) {
            this.MinusResult = MinusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SOA.Web.UnitTest.WebServiceTest.CustomSoapHeader CustomSoapHeader;
        
        public UserListRequest() {
        }
        
        public UserListRequest(SOA.Web.UnitTest.WebServiceTest.CustomSoapHeader CustomSoapHeader) {
            this.CustomSoapHeader = CustomSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SOA.Web.UnitTest.WebServiceTest.WebServiceUser[] UserListResult;
        
        public UserListResponse() {
        }
        
        public UserListResponse(SOA.Web.UnitTest.WebServiceTest.WebServiceUser[] UserListResult) {
            this.UserListResult = UserListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServiceSoapChannel : SOA.Web.UnitTest.WebServiceTest.MyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServiceSoapClient : System.ServiceModel.ClientBase<SOA.Web.UnitTest.WebServiceTest.MyWebServiceSoap>, SOA.Web.UnitTest.WebServiceTest.MyWebServiceSoap {
        
        public MyWebServiceSoapClient() {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA.Web.UnitTest.WebServiceTest.MinusResponse SOA.Web.UnitTest.WebServiceTest.MyWebServiceSoap.Minus(SOA.Web.UnitTest.WebServiceTest.MinusRequest request) {
            return base.Channel.Minus(request);
        }
        
        public int Minus(SOA.Web.UnitTest.WebServiceTest.CustomSoapHeader CustomSoapHeader, int iValueOne, int iValueTwo) {
            SOA.Web.UnitTest.WebServiceTest.MinusRequest inValue = new SOA.Web.UnitTest.WebServiceTest.MinusRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            inValue.iValueOne = iValueOne;
            inValue.iValueTwo = iValueTwo;
            SOA.Web.UnitTest.WebServiceTest.MinusResponse retVal = ((SOA.Web.UnitTest.WebServiceTest.MyWebServiceSoap)(this)).Minus(inValue);
            return retVal.MinusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA.Web.UnitTest.WebServiceTest.MinusResponse> SOA.Web.UnitTest.WebServiceTest.MyWebServiceSoap.MinusAsync(SOA.Web.UnitTest.WebServiceTest.MinusRequest request) {
            return base.Channel.MinusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA.Web.UnitTest.WebServiceTest.MinusResponse> MinusAsync(SOA.Web.UnitTest.WebServiceTest.CustomSoapHeader CustomSoapHeader, int iValueOne, int iValueTwo) {
            SOA.Web.UnitTest.WebServiceTest.MinusRequest inValue = new SOA.Web.UnitTest.WebServiceTest.MinusRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            inValue.iValueOne = iValueOne;
            inValue.iValueTwo = iValueTwo;
            return ((SOA.Web.UnitTest.WebServiceTest.MyWebServiceSoap)(this)).MinusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA.Web.UnitTest.WebServiceTest.UserListResponse SOA.Web.UnitTest.WebServiceTest.MyWebServiceSoap.UserList(SOA.Web.UnitTest.WebServiceTest.UserListRequest request) {
            return base.Channel.UserList(request);
        }
        
        public SOA.Web.UnitTest.WebServiceTest.WebServiceUser[] UserList(SOA.Web.UnitTest.WebServiceTest.CustomSoapHeader CustomSoapHeader) {
            SOA.Web.UnitTest.WebServiceTest.UserListRequest inValue = new SOA.Web.UnitTest.WebServiceTest.UserListRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            SOA.Web.UnitTest.WebServiceTest.UserListResponse retVal = ((SOA.Web.UnitTest.WebServiceTest.MyWebServiceSoap)(this)).UserList(inValue);
            return retVal.UserListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA.Web.UnitTest.WebServiceTest.UserListResponse> SOA.Web.UnitTest.WebServiceTest.MyWebServiceSoap.UserListAsync(SOA.Web.UnitTest.WebServiceTest.UserListRequest request) {
            return base.Channel.UserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA.Web.UnitTest.WebServiceTest.UserListResponse> UserListAsync(SOA.Web.UnitTest.WebServiceTest.CustomSoapHeader CustomSoapHeader) {
            SOA.Web.UnitTest.WebServiceTest.UserListRequest inValue = new SOA.Web.UnitTest.WebServiceTest.UserListRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            return ((SOA.Web.UnitTest.WebServiceTest.MyWebServiceSoap)(this)).UserListAsync(inValue);
        }
    }
}
